### ISSUE TITLE
Binary cache for AArch64

### ISSUE THREAD

**Issue by drakon64** [lilyinstarlight/nixos-cosmic#104]
I've been trying to build a Live ISO using this Flake so that I can test COSMIC without having to upgrade to NixOS Unstable. This is working fine for x86_64 (aside from what is probably upstream bugs) but the AArch64 images take hours to build and eventually fails due to Rust compiler errors (Nix didn't provide the full error and the build host is ephemeral so I can't provide the full log).

Far as I can tell almost every COSMIC package for the x86_64 image is coming from https://cosmic.cachix.org but AArch64 still has to be built from source.

Both architectures are configured with the same settings for [cachix-action](https://github.com/cachix/cachix-action).

The Flake that builds the ISO is locked to the same commit hashes as the Flake in this repository (i.e they should be building from the same version of NixOS Unstable).

**Comment by lilyinstarlight** [comment]
AArch64 builds fine (I just confirmed this now), the errors were likely due to resource exhaustion on your host if you did not reduce parallel jobs, since rustc is very expensive

AArch64 is not cached (except when I manually build and cache it) because GHA cannot build AArch64 without emulation, self-hosted builders, or paying for a GitHub Team/Enterprise plan and unfortunately none of those seem viable options. I do wish we had an option for that

I went ahead and at least pushed the latest `main` branch build for AArch64 and will continue to try to do that until there's a better option

**Comment by drakon64** [comment]
I've been trying to work out a better option. Currently I'm using an AWS CodeBuild instance as a self-hosted runner for GitHub Actions but that's probably going to get expensive.

Currently I'm thinking of just starting up an ARM VM somewhere and deploying it as a self-hosted runner, and saving the built derivations to a public Cachix cache.

**Comment by lilyinstarlight** [comment]
I mean if you have a builder and are comfy with sharing it, I'm happy to get it added to this repo and get it pushing to https://cosmic.cachix.org :)

**Comment by drakon64** [comment]
I've had another idea of starting an AArch64 runner in response to signed webhooks, so I'm going to have a crack at doing that. If all goes well, I'd be fine with sharing it with this repository.

**Comment by drakon64** [comment]
Good news, I've been able to get an ephemeral runner to start in response to a workflow being triggered (see https://github.com/drakon64/nixos-cosmic-iso/actions/runs/9159262191/job/25179497464).

I'm still working on some improvements but I should be able to provide an AArch64 runner for this repository soon. Unfortunately, adding runners requires Administrator access to the repository ([GitHub restriction](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-a-repository--fine-grained-access-tokens), unless you're on Enterprise).
