### ISSUE TITLE
Can't enable WiFi

### ISSUE THREAD

**Issue by cig0** [lilyinstarlight/nixos-cosmic#107]
Hi,

I just learned about this effort to bring COSMIC to NixOS -- THANK YOU ALL FOR YOUR WORK!

On a fully up-to-date COSMIC install, I can't enable WiFi. OTOH, Bluetooth works out of the box.

**Comment by cig0** [comment]
> WiFi for me works out of the box. Does it not appear as an option? Or maybe an issue with your WiFi card being supported? I am new to contributing to NixOS so don't mind me if the questions are silly

Hey, thanks for stepping in! The WiFi toggle is there, but it is grayed out, and I can't switch it. WiFi otherwise works OOTB with KDE.

**Comment by cig0** [comment]
I'm closing this issue to reduce noise here since this only seems to be affecting me. I'll try again in some time.

**Comment by maupind** [comment]
Fair enough, I just had a thought. What option are you using for enabling wifi? I believe there were a couple different options for this in NixOS

**Comment by cig0** [comment]
> Fair enough, I just had a thought. What option are you using for enabling wifi? I believe there were a couple different options for this in NixOS

Dang! I totally overlooked this! I’m using NetworkManager, should I try with `systemd-network`?

**Comment by lilyinstarlight** [comment]
NetworkManager is preferred and enabled by default now for nixos-cosmic

Can you `nmcli device` from a terminal and share your output?

**Comment by cig0** [comment]
Well, after updating my COSMIC installation, WiFi now works without issues 🎉

I also confirm I can log into my COSMIC session from SDDM, which is essential for me as a KDE fanboy :P

Regarding COSMIC's greeter, the first four options, starting with the accessibility button and ending with the configuration button, don't work for me. I'll open an issue to track this bug.

Thanks again, @maupind and @lilyinstarlight, for stepping in, and @lilyinstarlight, for actively working on having COSMIC available for us! 🤩
