### ISSUE TITLE
GTK3 Theming does not seem to work

### ISSUE THREAD

**Issue by KaiserCalm** [lilyinstarlight/nixos-cosmic#133]
I've seen it mentioned by mmstick that gtk3 theming should be suported in COSMIC if adw-gtk3 is also installed, however this does not seem to currently be the case in NixOS. Now whether is this a NixOS or a COSMIC issue I don't know how to check myself, so I thought I should report this here.

**Comment by KaiserCalm** [comment]
Should this module include an option for gtk3 support?

**Comment by lilyinstarlight** [comment]
This really sounds mostly irrelevant to COSMIC (e.g. if this is a libadwaita thing, I don't see why other libadwaita-based environments wouldn't suffer similarly), if you have config options that are useful to add for an "out of box" COSMIC experience, feel free to share them or make a PR

Only trouble is this would likely be most correctly set via GSettings overrides or dconf, and both are still a bit awkward with NixOS options (perhaps COSMIC should be setting/managing GTK theme itself even?)
