### ISSUE TITLE
Error on sudo nixos-rebuild switch

### ISSUE THREAD

**Issue by MrGamerDoesGames** [lilyinstarlight/nixos-cosmic#135]
Hello. I've followed the guide to a T (Add the stuff to the flake.nix file, save it in the /etc/nixos directory, run nix flake update in that directory, then nixos-rebuild switch.) But, on trying to rebuild switch, I get this error and it fails. `error: flake 'path:/etc/nixos' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."NixOSurface".config.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations."NixOSurface".config.system.build.nixos-rebuild' or 'nixosConfigurations."NixOSurface".config.system.build.nixos-rebuild'`

Maybe I'm doing a dumb mistake and don't realize it. I'm still new to NixOS and flakes. I'll attach my flake.nix here, and if anything else could help, it'd be appreciated. Thank you.

FLAKE.NIX:

[flake.txt](https://github.com/lilyinstarlight/nixos-cosmic/files/15487297/flake.txt)

(Saved and uploaded as a .txt file cause GitHub formatted it weird when I tried to just paste it in here. The actual file is named flake.nix in the right directory.)

**Comment by lilyinstarlight** [comment]
> # NOTE: change "host" to your system's hostname

That comment is a little relevant here. You need to change `host` to `NixOSurface` 😅

**Comment by MrGamerDoesGames** [comment]
> > `# NOTE: change "host" to your system's hostname`
> 
> That comment (from your `flake.nix`) is a little relevant here. You need to change `host` to `NixOSurface` 😅

I can't believe I screwed that up, thanks so much for clarifying. Before, I was trying to set the value _after_ host to my hostname. It now builds successfully. One little thing though, I now have to append --impure each time I want to rebuild my system. Any way to fix that? It says I'm in "traditional evaluation" mode with nixpkgs. I'm still new to NixOS, just started using it this month so I still want to learn it.

**Comment by lilyinstarlight** [comment]
What error message do you get when you don't use `--impure`?

I'll make instructions a bit clearer around `host` as well :)

**Comment by MrGamerDoesGames** [comment]
> What error message do you get when you don't use `--impure`?
> 
> I'll make instructions a bit clearer around `host` as well :)

Hi, I got this exact message:

`cannot look up '<nixpkgs>' in pure evaluation mode (use '--impure' to override)
(use '--show-trace' to show detailed location information)`

**Comment by lilyinstarlight** [comment]
Ah, are you using `<nixpkgs>` anywhere in your config? Feel free to ping me in [#users:nixos.org](https://matrix.to/#/%23users:nixos.org) on matrix for support too (and I or someone else can help)

**Comment by MrGamerDoesGames** [comment]
> Ah, are you using `<nixpkgs>` anywhere in your config? Feel free to ping me in [#users:nixos.org](https://matrix.to/#/%23users:nixos.org) on matrix for support too (and I or someone else can help)

Not quite sure what you mean, but I looked through configuration.nix and flake.nix and found this:

CONFIGURATION.NIX

`# Allow unfree packages
nixpkgs.config.allowUnfree = true;`

FLAKE.NIX

flake.nix is full of it. Basically all I have in my flake.nix is from this github repo, I don't use any other flakes. I can provide it if need be.

I'll also get Matrix, it seems interesting. What's the best client for it on COSMIC? (By that I mean fastest, most well-integrated with theming and the desktop and such.)
