### ISSUE TITLE
cosmic update action is failing

### ISSUE THREAD

**Issue by michaelBelsanti** [lilyinstarlight/nixos-cosmic#217]
The build is failing because as Lily has removed herself from the nixpkgs maintainers list, but is listed as the maintainer of many of the packages here. 

I'll open a PR for this, but I don't have access to my computer atm, in case anyone wants to fix it in the meantime :)

**Comment by drakon64** [comment]
I've currently got an ugly hack that comments out the maintainers list entirely (turns out it's not mandatory). If someone can add a maintainer within the Flake, that would be far better.
