### ISSUE TITLE
cosmic-store and cosmic-task are not being installed

### ISSUE THREAD

**Issue by Thatoo** [lilyinstarlight/nixos-cosmic#224]
Are all pkgs from https://github.com/lilyinstarlight/nixos-cosmic/tree/main/pkgs supposed to get installed with this flakes?
I guess it should but it doesn't.
Actually, I feel it's been quiet some time cosmic didn't get updated in my computer.
Can it be because I'm trying to use "specialisation"?

```
  # Enable the X11 windowing system.
  services.xserver = {
    enable = true;
    displayManager.gdm.enable = lib.mkDefault true;
    desktopManager.gnome.enable = lib.mkDefault true;
  };

  specialisation = {
    gnome.configuration = {
      services.xserver = {
        desktopManager.gnome.enable = true;
        displayManager.gdm.enable = true;
      };
      system.nixos.tags = [ "Gnome" ];
    };
    cosmic.configuration = {
      # Cosmic conflicts with gnome
      services.xserver.desktopManager.gnome.enable = false;
      services.desktopManager.cosmic.enable = true;
        # Cosmic requires cosmic-greeter
      services.xserver.displayManager.gdm.enable = false;
      services.displayManager.cosmic-greeter.enable = true;

      system.nixos.tags = [ "Cosmic" ];
    };
  };
}


```

**Comment by drakon64** [comment]
COSMIC Store should be installed automatically if you have Flatpak enabled.

COSMIC Tasks is not automatically installed, but I assume it's installed the same as any other package is.

This repository hasn't seen much activity recently, but new COSMIC builds are currently broken on all supported NixOS versions anyway so there will be no updates for the time being.

**Comment by Thatoo** [comment]
I see. Then, what is https://github.com/lilyinstarlight/nixos-cosmic/blob/main/pkgs/cosmic-store/package.nix for ? I'm confused.

**Comment by drakon64** [comment]
That's the COSMIC Store package which is automatically installed if you have Flatpak enabled

**Comment by Thatoo** [comment]
So I'll try adding it into the specialization like :

```
    cosmic.configuration = {
      # Cosmic conflicts with gnome
      services.xserver.desktopManager.gnome.enable = false;
      services.desktopManager.cosmic.enable = true;
        # Cosmic requires cosmic-greeter
      services.xserver.displayManager.gdm.enable = false;
      services.displayManager.cosmic-greeter.enable = true;

      services.flatpak.enable = true;

      system.nixos.tags = [ "Cosmic" ];
    };
```

**Comment by Thatoo** [comment]
It works
