### ISSUE TITLE
The option `hardware.graphics' does not exist

### ISSUE THREAD

**Issue by Thatoo** [lilyinstarlight/nixos-cosmic#226]
Everything was working till last week-end I guess.
Today, i did
```
sudo nix flake update
sudo nixos-rebuild switch --show-trace --flake
```
and it failed with
```
error:
       … while calling the 'seq' builtin

         at /nix/store/sj9yrq21wbbfr5715hys3laa2qd6x471-source/lib/modules.nix:322:18:

          321|         options = checked options;
          322|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          323|         _module = checked (config._module);

       … while calling the 'throw' builtin

         at /nix/store/sj9yrq21wbbfr5715hys3laa2qd6x471-source/lib/modules.nix:298:18:

          297|                     ''
          298|             else throw baseMsg
             |                  ^
          299|         else null;

       error: The option `hardware.graphics' does not exist. Definition values:
       - In `/nix/store/sv3hw54ha6n92nrh5f8ki3vb602q52w8-source/nixos/cosmic-greeter/module.nix':
           {
             _type = "if";
             condition = false;
             content = {
               enable = true;
           ...
```

Any idea what it could be?

**Comment by lilyinstarlight** [comment]
Yes, due to upstream requiring a newer rustc than nixpkgs intends to backport to stable, 24.05 support has been dropped. You'll need nixos-unstable going foward

**Comment by Thatoo** [comment]
Something like
```
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    nixpkgs_unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
```

isn't possible?

**Comment by lilyinstarlight** [comment]
> Something like
> 
> ```
>   inputs = {
>     nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
>     nixpkgs_unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
> ```
> 
> isn't possible?

I mean if you use `nixpkgs_unstable.lib.nixosSystem` then that could work I guess. The important bit is that your system is built against nixos-unstable rather than whatever your flake inputs ultimately have

**Comment by Thatoo** [comment]
Thank you even though that's sad. I wish Gnome specialisation and software packages could be stable and only cosmic sepcialisation could be unstable...

**Comment by lilyinstarlight** [comment]
Yeah it is, I would have continued making it work with both, but cosmic upstream bumped rustc version to the most recently released version and nixpkgs has stated they don't want to backport that version to stable :/

**Comment by lilyinstarlight** [comment]
Fortunately nixos-unstable isn't that much different than stable for desktop/workststion use-case aside from software generally being newer

**Comment by Thatoo** [comment]
Thank you for your work, your effort, your time and your explanation.

**Comment by drakon64** [comment]
@Thatoo Support for NixOS Stable was re-added in https://github.com/lilyinstarlight/nixos-cosmic/commit/39c6d797e80ecbe4878b10b8341d723da4fc3d71

**Comment by Tommimon** [comment]
> @Thatoo Support for NixOS Stable was re-added in [39c6d79](https://github.com/lilyinstarlight/nixos-cosmic/commit/39c6d797e80ecbe4878b10b8341d723da4fc3d71)

Do caches work for you when using NixOS Stable? I have to compile all the COSMIC components.

**Comment by drakon64** [comment]
Caches work fine for me on Stable

**Comment by lilyinstarlight** [comment]
Closing since this has been resolved
