### ISSUE TITLE
ctrl+space not working in Cosmic Terminal

### ISSUE THREAD

**Issue by onsails** [lilyinstarlight/nixos-cosmic#228]
I'm using Emacs which works well under Cosmic when running in gui mode. However if I run emacs in Cosmic Terminal, it fails to correctly process `ctrl+space`: it just prints a space while it should start text selection. It's certainly not a emacs configuration issue because it's reproducing with `emacs -Q -nw`.

I've also noticed that, if I set compose key, `ctrl+c` stops working in terminal (no emacs) but after setting it to None it got back to normal.

**Comment by eliasboegel** [comment]
You should probably raise this issue in [cosmic-term](https://github.com/pop-os/cosmic-term). This repository is only for packaging cosmic for NixOS.
