### ISSUE TITLE
Upstream the modules?

### ISSUE THREAD

**Issue by musjj** [lilyinstarlight/nixos-cosmic#245]
The first alpha release is now out: https://system76.com/cosmic

Maybe it's time to upstream the NixOS modules? All the required packages is already in nixpkgs from the looks it: https://github.com/NixOS/nixpkgs/issues/259641 (except for `cosmic-player`).

**Comment by lilyinstarlight** [comment]
Hi there!

The packages in Nixpkgs definitely need fixes from this repo before the module would even begin to work with them

Although I had originally intended to upstream the stuff here, [I'm no longer interacting with Nixpkgs](https://github.com/NixOS/nixpkgs/pull/323903) and will therefore continue to do my own maintenance here instead

Anyone is of course welcome to copy-paste anything in this repository back to Nixpkgs (following the license terms) however :)

Thanks for checking!
