### ISSUE TITLE
Home Manager Standalone support

### ISSUE THREAD

**Issue by mjakobsche** [lilyinstarlight/nixos-cosmic#270]
Hi,
Is it possible to use this flake in HM standalone? Or is there any workaround I could do?

**Comment by zarMarco** [comment]
i'm interested too

**Comment by Jeidnx** [comment]
This flake has nothing to do with home-manager.Do you mean to configure the desktop? There is a PR [here](https://github.com/nix-community/home-manager/pull/5695) which you can build home-manager from and it should work.
If you mean running cosmic trough home-manager *without nixos*, then no, that will not work.

**Comment by mjakobsche** [comment]
Okay. Thanks

**Comment by izelnakri** [comment]
> If you mean running cosmic trough home-manager without nixos, then no, that will not work.

I would love to run cosmic desktop on my devices with arch linux or android, *without going through their respective/manual package manager setup*. Could we reopen this issue @mjakobsche and get a home-manager support? @Jeidnx

**Comment by drakon64** [comment]
But this Flake isn't for Home Manager, it's for NixOS. Home Manager is a completely different setup.

**Comment by lilyinstarlight** [comment]
> But this Flake isn't for Home Manager, it's for NixOS. Home Manager is a completely different setup.

We could add a standalone module, but you're really gonna probably want to just go with whatever OS-specific setup is available for COSMIC, for a variety of reasons

So yeah I'll mention if the plans change, but I have no plans to try to make COSMIC work from an HM module

**Comment by zarMarco** [comment]
> But this Flake isn't for Home Manager, it's for NixOS. Home Manager is a completely different setup.

Yes I know, but I can use flake with home-manager

**Comment by mjakobsche** [comment]
On one hand - we have Sway, which can be handled completely by hm standalone. 
Cosmic however includes many more components, which also need to os-level access, not only user environment, if I understood it correctly. So I guess it would require a lot of effort to make it work. :(

**Comment by mjakobsche** [comment]
As for the OS-specific setup - well, my favourite part about hm standalone is that it allows users to omit os-specific setups ;P
So yeah It’d be great to have one day ;>>
