### ISSUE TITLE
Can't handle WiFi

### ISSUE THREAD

**Issue by Thatoo** [lilyinstarlight/nixos-cosmic#271]
Hello,

I face the same issue as https://github.com/lilyinstarlight/nixos-cosmic/issues/107

Wifi connects automatically but I can't handle WiFi from Cosmic. Bluetooth works out of the box.

The Wifi toggle is there, but it is grayed out, and I can't switch it and I can't find any wifi settings.

![image](https://github.com/user-attachments/assets/3bc7e289-5dae-4593-9983-07ebcd6f781b)

```
:~$ nmcli device
DEVICE          TYPE      STATE                  CONNECTION
wlp4s0          wifi      connecté               FREEWIFI
lo              loopback  connecté (en externe)  lo
p2p-dev-wlp4s0  wifi-p2p  déconnecté             --
enp0s31f6       ethernet  indisponible           --
vboxnet0        ethernet  non-géré               --
```

**Comment by Thatoo** [comment]
Wifi settings ave arrived within Cosmic settings app but the wifi applet is still not working properly, same as previously described.

**Comment by drakon64** [comment]
How is your networking configured? I can't reproduce this.

**Comment by drakon64** [comment]
How is your networking configured?

**Comment by Thatoo** [comment]
in configuration.nix, I have simply : 
```
  networking.hostName = "LaptopName"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Enable networking
  networking.networkmanager.enable = true;
```
and nothing about it in my specialisation.nix file

How should it be?

On a different but linked issue, upstream, I got this answer, https://github.com/pop-os/cosmic-epoch/issues/976#issuecomment-2363334960, can it be related?

**Comment by Thatoo** [comment]
I'll try adding something like this : 
  specialisation = {
    cosmic.configuration = {
      environment.systemPackages = with pkgs; [
        networkmanagerapplet
        gnome.networkmanager-openvpn
      ];
      system.nixos.tags = [ "Cosmic" ];
    };
  };

**Comment by Thatoo** [comment]
It has indeed solved this issue https://github.com/pop-os/cosmic-epoch/issues/976#issuecomment-2363334960 and also it has added a wifi option among applets but it doesn't feel quiet right (not very integrated. I'd be interested to see how it should look like by the way).

![image](https://github.com/user-attachments/assets/4ab2b1ea-7c1a-4023-88ce-f4977feb9023)

is the new wifi option among applets
and

![image](https://github.com/user-attachments/assets/40719fed-2bb4-4de9-beca-0d7a60027502)

is the same as before : no icon and impossible to switch wifi toggles.

**Comment by Wasabi375** [comment]
I have a similar issue. The Wi-Fi toggle is working fine for me, but I can't connect to any network. 

When I try it shows an error message:
![image](https://github.com/user-attachments/assets/4558b519-a28a-4a8f-9c7d-f95de73b3f7c)

Sometimes it also thinks that I entered the wrong password:
![image](https://github.com/user-attachments/assets/e4caa1bf-503d-427b-93f0-4b33fc569334)

I checked multiple times and the password is correct.

I tried the workaround above and I am able to connect using the network manager applet.

**Comment by graysonhead** [comment]
I have the same issue. I cannot toggle anything with the Cosmic network app, but I can change network seetings either via nmcli or via the network settings page in cosmic.

I found the following error, which I'm guessing is the cause:
```
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork: thread 'tokio-runtime-worker' panicked at cosmic-applet-network/src/network_manager/mod.rs:365:44:
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork: called `Result::unwrap()` on an `Err` value: MethodError(OwnedErrorName("org.freedesktop.NetworkManager.Settings.PermissionDenied"), Some("uid 1000 has no permission to perform this operation"), Msg { type: Error, serial: 1033, sender: UniqueName(":1.11"), reply-serial: 192, body: Signature("s"), fds: [] })
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork: stack backtrace:
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:    0: rust_begin_unwind
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:    1: core::panicking::panic_fmt
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:    2: core::result::unwrap_failed
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:    3: cosmic_applet_network::network_manager::NetworkManagerState::new::{{closure}}
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:    4: cosmic_applet_network::network_manager::start_listening::{{closure}}
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:    5: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:    6: <futures_util::stream::select::Select<St1,St2> as futures_core::stream::Stream>::poll_next
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:    7: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:    8: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:    9: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:   10: iced_futures::subscription::tracker::Tracker::update::{{closure}}
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:   11: tokio::runtime::task::raw::poll
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:   12: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork:   13: tokio::runtime::task::raw::poll
Oct 11 10:56:25 deckchair .cosmic-panel-wrapped[2694]: com.system76.CosmicAppletNetwork: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

uid 1000 is my user, and I am in both wheel and the networkmanager group, and I'm not sure why this permissions error is occurring.

**Comment by Thatoo** [comment]
The issue is still here on alpha 3

**Comment by Thatoo** [comment]
I think I found out my issue. I deleted all past connection setting that were containing a WEP wifi password, reboot and now the network applet display and is working.
