### ISSUE TITLE
Clicking on URL don't open default browser

### ISSUE THREAD

**Issue by Thatoo** [lilyinstarlight/nixos-cosmic#273]
I have

```
~$ xdg-settings get default-web-browser
firefox.desktop
```

but when I click on a URL, written in an email in Thunderbird or in a message in Element, nothing happen.

Is it because of Wayland?
Can it be linked to the fact I use "specialisations" and can start either under Gnome X11 or Cosmic Wayland?

**Comment by RAVENz46** [comment]
I hope adding this lines to your config fix temporary.
In the future, this might be fixed by removing xdg-desktop-portal-gtk from extraPortals ([mentioned here](https://github.com/lilyinstarlight/nixos-cosmic/issues/57#issuecomment-2286795771)).

```nix
systemd.user.extraConfig = ''
  DefaultEnvironment="PATH=/run/wrappers/bin:/etc/profiles/per-user/%u/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"
'';
```

**Comment by Thatoo** [comment]
This does indeeed solve the issue.
```
    cosmic.configuration = {
      # Cosmic conflicts with gnome
      services.xserver.desktopManager.gnome.enable = false;
      services.desktopManager.cosmic.enable = true;
        # Cosmic requires cosmic-greeter
      services.xserver.displayManager.gdm.enable = false;
      services.displayManager.cosmic-greeter.enable = true;

      services.flatpak.enable = true;

      systemd.user.extraConfig = ''DefaultEnvironment="PATH=/run/wrappers/bin:/etc/profiles/per-user/%u/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"'';

      system.nixos.tags = [ "Cosmic" ];
    };
```

Thank you @RAVENz46

**Comment by Thatoo** [comment]
Will I need to remove it in future when it will be solved by "removing xdg-desktop-portal-gtk from extraPortals"?

**Comment by lilyinstarlight** [comment]
> Will I need to remove it in future when it will be solved by "removing xdg-desktop-portal-gtk from extraPortals"?

It will need to be removed when we make cosmic import env vars into systemd user environment like it's supposed to. I can poke this issue when that occurs if you'd like (I'd meant to implement it as outlined in Matrix by now, but life stuff keeps coming up...)

**Comment by Thatoo** [comment]
That would be really sweet of you to poke this issue when you manage to find time to implement the proper solution. Take care of yourself. Kind regards,
