### ISSUE TITLE
Method to exclude default COSMIC apps

### ISSUE THREAD

**Issue by eliasboegel** [lilyinstarlight/nixos-cosmic#274]
The KDE packaging for NixOS includes a way to exclude Plasma applications from being installed: https://nixos.wiki/wiki/KDE

I would love it if the same was possible here. For instance, I can see many people using a different terminal emulator, text editor and file manager. As far as I can tell, there is currently no way to exclude any default packages.

**Comment by lilyinstarlight** [comment]
[`environment.cosmic.excludePackages` does exist](https://github.com/lilyinstarlight/nixos-cosmic/blob/04a0f18cf0a4f1499d8abec419bd92e87cb05157/nixos/cosmic/module.nix#L16-L21), is that sufficient?

**Comment by RAVENz46** [comment]
Yes, you can do it exactly same way.
All excludable packages are listed [here](https://github.com/lilyinstarlight/nixos-cosmic/blob/04a0f18cf0a4f1499d8abec419bd92e87cb05157/nixos/cosmic/module.nix#L34)
Here is an example.

```nix
      environment = {
        cosmic.excludePackages = with pkgs; [
          adwaita-icon-theme
          cosmic-edit
          cosmic-files
          cosmic-launcher
          cosmic-term
          hicolor-icon-theme
          pop-icon-theme
          pop-launcher
        ];
      };
```

**Comment by eliasboegel** [comment]
My bad. I must have missed it. Thanks a lot!
