### ISSUE TITLE
quick-webapps

### ISSUE THREAD

**Issue by Thatoo** [lilyinstarlight/nixos-cosmic#280]
When https://github.com/NixOS/nixpkgs/pull/322226 is merged and the Nixos package is ready, will you add it to your flake? I can ping here when it's ready if you want.

**Comment by lilyinstarlight** [comment]
Added in <https://github.com/lilyinstarlight/nixos-cosmic/commit/0bf8cad9a9c37a4a1244aa642c0df968856142b2>
