### ISSUE TITLE
Slow perfomance and lack of snapiness

### ISSUE THREAD

**Issue by aacebedo** [lilyinstarlight/nixos-cosmic#290]
I tried a bit COSMIC and find it pretty promising.
However I noticed that on my FW13 AMD 7840U, it is pretty slow to open apps (2 to 4 seconds for opening settings or files).
It is even worst when I switch to battery power profile. I do not notice such slowdowns when using other WM or DEs such as Gnome, sway or Hyprland on the same machine.

Is it a normal behavior? Does the flake use the correct optimization compile flags?

**Comment by drakon64** [comment]
The optimisation flags should be set by the upstream project and not the Flake. By default Nix should be compiling using [Cargo's release profile](https://doc.rust-lang.org/cargo/reference/profiles.html#release).

**Comment by aacebedo** [comment]
Thanks for the answer.

Did anyone noticed the same behavior? If it is not the case I wonder from where it is coming.

**Comment by eliasboegel** [comment]
Yes, I have the same behavior.

**Comment by lilyinstarlight** [comment]
If anyone can provide comparisons against COSMIC Pop OS for their machine, that would be helpful. Otherwise I'm not sure this report of upstream issues is actionable

**Comment by aacebedo** [comment]
> If anyone can provide comparisons against COSMIC Pop OS for their machine, that would be helpful. Otherwise I'm not sure this report of upstream issues is actionable

I won't be able to install cosmic pop os on my machine as it is my daily driver.

I'll try alpha 2 to see if something has changed and post the results here.

I understand that the feedback is difficult to leverage but I was unable to gather anything else than my experience using it (didn't found suspect logs for instance) .

I close the ticket to avoid polluting the backlog.

**Comment by aacebedo** [comment]
Tested with alpha 2. Unfortunately, same result.

There is nothing significant in the terminal.
