### ISSUE TITLE
Cosmic Calculator

### ISSUE THREAD

**Issue by Thatoo** [lilyinstarlight/nixos-cosmic#291]
When https://github.com/NixOS/nixpkgs/issues/337554 will have a Nixos package, I can ping here if you're willing to add it to this flake.

**Comment by lilyinstarlight** [comment]
Added in <https://github.com/lilyinstarlight/nixos-cosmic/commit/091c4b039162c19068af6ca135e78bec1cb6ad80>

**Comment by Thatoo** [comment]
Hello,
How can I benefit from this improvement?
I did 
```
sudo nix flake update
sudo nixos-rebuild switch --show-trace --flake .#default
```
and rebooted my computer and can't find it. Should I add it to the list
```
  specialisation = {
    cosmic.configuration = {

      environment.systemPackages = with pkgs; [
        loupe
      ];

      system.nixos.tags = [ "Cosmic" ];
    }
  }
```
?

**Comment by drakon64** [comment]
You add it to `environment.systemPackages` then rebuild as normal

**Comment by Thatoo** [comment]
it stop working for
        cosmic-calculator
        cosmic-forecast
        cosmic-tweaks
Is there any reason?

**Comment by lilyinstarlight** [comment]
They were renamed per upstream to `cosmic-ext-calculator`, `cosmic-ext-forecast`, and `cosmic-ext-tweaks` to differentiate official/unofficial cosmic apps

**Comment by lilyinstarlight** [comment]
I should probably add helpful error messages when I rename packages though, oops
