### ISSUE TITLE
Cosmic UIs have no text

### ISSUE THREAD

**Issue by 21eleven** [lilyinstarlight/nixos-cosmic#298]
No text is shown on the cosmic greeter or on any of the cosmic apps once logged in. For example the display section of the settings UI looks like this:

![image](https://github.com/user-attachments/assets/99d945f0-5505-48c4-82f9-c5eafd1b1b67)

100% of the cosmic ui suffers from this issue. I went on a random walk through the screenshot applet to get the above screen since it also has the problem. Non-cosmic apps like my terminal (Alacritty) or Firefox behave normally.

I am using nixos-unstable, x86-64.

This issue sounds similar to #285. 

> The user selection contains one entry, with a checkmark in front of it, but there is no username displayed. So it's an empty label with a checkmark next to it.

This description matches how the greeter UI looks to me. However if I enter my user's password into what is, evidently, the password box I get logged in to the desktop.

**Comment by 21eleven** [comment]
Switching to nixos-24.05 nixpkgs fixed this issue for me

**Comment by xpar-vitalii** [comment]
Hmm, seems like something to do with the dependencies then, nixpkgs vendored bad version of iced/cosmic-text/rusttype?

**Comment by tukanoidd** [comment]
(Realized that I used my work account first, so removed comment from that one) Hmm, seems like something to do with the dependencies then, nixpkgs vendored bad version of iced/cosmic-text/rusttype?

**Comment by lilyinstarlight** [comment]
> (Realized that I used my work account first, so removed comment from that one) Hmm, seems like something to do with the dependencies then, nixpkgs vendored bad version of iced/cosmic-text/rusttype?

Nixpkgs doesn't vendor any of that. Upstream defines versions in their lockfile

This is an upstream nixpkgs issue regardless and has little to do with cosmic (especially given it's affecting pretty much all DEs to some degree), see <https://github.com/NixOS/nixpkgs/issues/338933>

**Comment by tukanoidd** [comment]
> > (Realized that I used my work account first, so removed comment from that one) Hmm, seems like something to do with the dependencies then, nixpkgs vendored bad version of iced/cosmic-text/rusttype?
> 
> Nixpkgs doesn't vendor any of that. Upstream defines versions in their lockfile
> 
> This is an upstream nixpkgs issue regardless and has little to do with cosmic (especially given it's affecting pretty much all DEs to some degree), see <https://github.com/NixOS/nixpkgs/issues/338933>

Fair, I'm not too knowledgeable on this topic, so was just spitballing. Thanks for the info! Now it makes sense why I might be having font issues with Rio as well
