### ISSUE TITLE
Cosmic Forecast

### ISSUE THREAD

**Issue by Thatoo** [lilyinstarlight/nixos-cosmic#311]
When https://github.com/NixOS/nixpkgs/issues/340124 will have a Nixos package, I can ping here if you're willing to add it to this flake.

**Comment by lilyinstarlight** [comment]
Added in https://github.com/lilyinstarlight/nixos-cosmic/commit/678ba77a0115441b675ff10135b8fd40060c36c4

**Comment by Thatoo** [comment]
Who is coding faster than her shadow?
