### ISSUE TITLE
Cosmic Wallpapers

### ISSUE THREAD

**Issue by molecule31** [lilyinstarlight/nixos-cosmic#315]
building last commit [7f2eeab](https://github.com/lilyinstarlight/nixos-cosmic/commit/7f2eeab5effffcd12c61b068e774f14c41bb7cee) gives error on rebuilding

```
       error: undefined variable 'cosmic-wallpapers'

       at /nix/store/669vkqg376qq6gd1gyrrh2r9f9rwp6h5-source/nixos/cosmic/module.nix:60:7:

           59|       cosmic-term
           60|       cosmic-wallpapers
             |       ^
           61|       cosmic-workspaces-epoch
```

regression down to the [3ec7895](https://github.com/lilyinstarlight/nixos-cosmic/commit/3ec78954adb0dfb7a54eb11c10a64946273fac46) when cosmic-wallpapers became default

**Comment by lilyinstarlight** [comment]
Can you share details about your configuration?

Cosmic-wallpapers package was added in <https://github.com/lilyinstarlight/nixos-cosmic/commit/ecc19584d4a4b9edfec21dccd25391cdc9656fcb> (which came before <https://github.com/lilyinstarlight/nixos-cosmic/commit/3ec78954adb0dfb7a54eb11c10a64946273fac46>) and I cannot replicate any regression on any nixos-unstable or nixos-24.05 configuration I can come up with

**Comment by TheNightmanCodeth** [comment]
Also facing this. I wound up forking and commenting that line out to get my builds back up this morning. My config is [here](https://github.com/TheNightmanCodeth/nixconfig/tree/main) if you'd like to take a look (I'm still learning all this so it's not very good). flake.nix and hosts/desktop.nix are probably the most interesting for this.

**Comment by lilyinstarlight** [comment]
> Also facing this. I wound up forking and commenting that line out to get my builds back up this morning. My config is [here](https://github.com/TheNightmanCodeth/nixconfig/tree/main) if you'd like to take a look (I'm still learning all this so it's not very good). flake.nix and hosts/desktop.nix are probably the most interesting for this.

Link is a 404 for me

**Comment by TheNightmanCodeth** [comment]
Sorry, try again?
Didn't mean to make private

**Comment by lilyinstarlight** [comment]
`pkgs` should never be in specialArgs and very likely to break things <https://github.com/TheNightmanCodeth/nixconfig/blob/392070c3799fbd08054ada71c995f7e17cd28330/flake.nix#L40>

Can you try to refactor that out so that the nixpkgs config options are actually respected instead of silently ignored from the config?

**Comment by TheNightmanCodeth** [comment]
Yeah felt wrong while I was doing it but I was being lazy. Seems to have cleared things up for me. 

Thanks for helping out with that

**Comment by lilyinstarlight** [comment]
> Yeah felt wrong while I was doing it but I was being lazy. Seems to have cleared things up for me.
> 
> Thanks for helping out with that

Ah, I'm glad it was at least that simple of a fix then :)

I wonder if nixpkgs could make that actually warn when nixpkgs options are ignored like that 🤔 (I was fairly certain it did but maybe it isn't smart enough to deal with the specialArgs case)

**Comment by molecule31** [comment]
> `pkgs` should never be in `specialArgs` and doing so is very likely to break things https://github.com/TheNightmanCodeth/nixconfig/blob/392070c3799fbd08054ada71c995f7e17cd28330/flake.nix#L40
> 
> Can you try to refactor that out so that the nixpkgs config options are actually respected instead of silently ignored from the config?

yeah removing `pkgs` from `specialArgs` fixed the issue! thanks!

**Comment by LunNova** [comment]
oh no, I was deliberately doing that to avoid nixpkgs getting evaled multiple times.

[`nixos/modules/misc/nixpkgs/read-only.nix`](https://github.com/NixOS/nixpkgs/blob/e9860fa6a9d56f1e2794bf946b5b1aa08722010f/nixos/modules/misc/nixpkgs/read-only.nix#L1-L10)

**Comment by lilyinstarlight** [comment]
> oh no, I was deliberately doing that to avoid nixpkgs getting evaled multiple times.
> 
> [`nixos/modules/misc/nixpkgs/read-only.nix`](https://github.com/NixOS/nixpkgs/blob/e9860fa6a9d56f1e2794bf946b5b1aa08722010f/nixos/modules/misc/nixpkgs/read-only.nix#L1-L10)

You can add the overlay yourself and import the files from module-list.nix manually via something like:

```nix
{ self, ... }:

{
  imports = import "${self.inputs.nixos-cosmic}/nixos/module-list.nix";
}
```

instead of using the [default entrypoint](https://github.com/lilyinstarlight/nixos-cosmic/blob/899e91d8433b598c6959bf3f7c927a06c62eefe1/nixos/default.nix)

Is that adequate?
