### ISSUE TITLE
pkgs/cosmic-notifications/package.nix has invalid meta attribute "mainPrograms"

### ISSUE THREAD

**Issue by Frontear** [lilyinstarlight/nixos-cosmic#316]
Fails to evaluate on my machine because the expected attribute is `meta.mainProgram` (without the "s").

Nix Version: `nix (Lix, like Nix) 2.92.0-devpre20240830_d75df91`

**Comment by lilyinstarlight** [comment]
Oops, nice catch! I'll fixed that now
