### ISSUE TITLE
Unresponsive cosmic-greeter on initial startup with external displays

### ISSUE THREAD

**Issue by cfrenette** [lilyinstarlight/nixos-cosmic#319]
Cosmic-greeter hangs (the UI doesn't react to any input) if external displays are connected to my laptop on initial startup. 

If the external displays are initially disconnected and then connected after logging in (with user settings loaded) then cosmic-greeter behaves as expected if it is run again, e.g. if the screen is locked.

I've attached log output when observing this issue. I think something about how cosmic-comp defaults display configuration when there is no system-level configuration files might be causing cosmic-greeter to hang in my case.

[journal.log](https://github.com/user-attachments/files/16923696/journal.log)

**Comment by lilyinstarlight** [comment]
This appears to be some upstream issue, possibly related to https://github.com/pop-os/cosmic-greeter/issues/108

**Comment by chr314** [comment]
just updated and it works now

**Comment by lilyinstarlight** [comment]
@cfrenette, can you confirm if it's working for you now? If so this issue can be closed

**Comment by cfrenette** [comment]
I was able to get a working cosmic-greeter on initial startup with at least one of my two external displays working (I'm pretty sure the other monitor not working is a separate issue unrelated to COSMIC / `cosmic-greeter`), so I think this issue is resolved.

Thanks!
