### ISSUE TITLE
Cosmic-greeter does not autostart so lockscreen won't work

### ISSUE THREAD

**Issue by FriederHannenheim** [lilyinstarlight/nixos-cosmic#346]
Since a update a few days ago cosmic-greeter does not start in the cosmic session and so locking the screen does not work. Starting cosmic-greeter manually and locking the screen works.

Edit: seems to be a bit hit-and-miss whether it starts. I just logged in again and it started.

**Comment by lilyinstarlight** [comment]
It's ra race condition I've worked with upstream already to root out

I haven't submitted the PR yet though but I'll link it when I do

**Comment by lilyinstarlight** [comment]
Fixed in https://github.com/pop-os/cosmic-greeter/pull/130

**Comment by lilyinstarlight** [comment]
Given this should be solved now, I'm going to close this. Feel free to reopen if you continue having issues after updating!
