### ISSUE TITLE
COSMIC Screenshot app crashes on start

### ISSUE THREAD

**Issue by Tommimon** [lilyinstarlight/nixos-cosmic#356]
I can't start COSMIC Screenshot form the launcher or by pressing `Print`, nothing happens.

If I try to run `cosmic-screenshot` from the terminal I get:

```
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.31"))), reply-serial: 17, body: Signature("s") }))
stack backtrace:
   0:     0x555721041295 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h1b9dad2a88e955ff
   1:     0x555721065b6b - core::fmt::write::h4b5a1270214bc4a7
   2:     0x55572103e41f - std::io::Write::write_fmt::hd04af345a50c312d
   3:     0x5557210423e1 - std::panicking::default_hook::{{closure}}::h96ab15e9936be7ed
   4:     0x5557210420bc - std::panicking::default_hook::h3cacb9c27561ad33
   5:     0x555721042a41 - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
   6:     0x5557210428a7 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
   7:     0x555721041759 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
   8:     0x555721042534 - rust_begin_unwind
   9:     0x555720d901d3 - core::panicking::panic_fmt::h3d8fc78294164da7
  10:     0x555720d906a6 - core::result::unwrap_failed::hfa79a499befff387
  11:     0x555720db5066 - cosmic_screenshot::main::{{closure}}::hab141b8d096c4547
  12:     0x555720e6db51 - tokio::runtime::scheduler::current_thread::Context::enter::hc8fec64add800ab6
  13:     0x555720e58cfb - tokio::runtime::context::scoped::Scoped<T>::set::hf39507ce94a5c345
  14:     0x555720e6dd1d - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::h71fcc4d1b14af4c5
  15:     0x555720e66411 - tokio::runtime::context::runtime::enter_runtime::he6eeffa048ed6bbe
  16:     0x555720e9dd7c - tokio::runtime::runtime::Runtime::block_on::hf92938d3260afc0c
  17:     0x555720e8abd8 - cosmic_screenshot::main::hb119801478c2ff13
  18:     0x555720e8bf23 - std::sys::backtrace::__rust_begin_short_backtrace::h9ede665277a82e5c
  19:     0x555720e5b879 - std::rt::lang_start::{{closure}}::hf37edf2992ca36ca
  20:     0x555721039260 - std::rt::lang_start_internal::h5e7c81cecd7f0954
  21:     0x555720e8aca5 - main
  22:     0x7f3882bd310e - __libc_start_call_main
  23:     0x7f3882bd31c9 - __libc_start_main@GLIBC_2.2.5
  24:     0x555720d90a65 - _start
  25:                0x0 - <unknown>
```

From what I read around screenshot app seams to work, so I wonder why this is happening to me. This is 100% reproducible and crashes every time I try to launch it.

**Comment by lilyinstarlight** [comment]
Can you `journalctl | grep -F xdg-desktop-portal-cosmic` and share?

**Comment by Tommimon** [comment]
I get this output:

```
set 21 16:06:02 hostname cosmic-session[1992]: starting process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=68 PORTAL_WAYLAND_SOCKET=66 /nix/store/653ngm4zfvwnffdxix8ih4gwdi6j790k-xdg-desktop-portal-cosmic-1.0.0-alpha.1-unstable-2024-09-14/bin/xdg-desktop-portal-cosmic '
set 21 16:06:02 hostname systemd[1939]: Started xdg-desktop-portal-cosmic.scope.
set 21 18:53:30 hostname cosmic-session[2136]: starting process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=68 PORTAL_WAYLAND_SOCKET=66 /nix/store/653ngm4zfvwnffdxix8ih4gwdi6j790k-xdg-desktop-portal-cosmic-1.0.0-alpha.1-unstable-2024-09-14/bin/xdg-desktop-portal-cosmic '
set 21 18:53:30 hostname systemd[2101]: Started xdg-desktop-portal-cosmic.scope.
```

But is not related to when I try to launch `cosmic-screenshot`. I get this output after a random delay.
Is it helpful?

**Comment by freeklucas** [comment]
From what I see, I'm getting the exact same issue.
In case it's relevant, here's some more information about my setup.

**System details:**
-  NixOS Version: 24.11 (Up-to-date as of writing this)
- Kernel: Linux 6.11.0
- I installed Cosmic using the Flake, which is imported under imports in my configuration.nix
- I'm using TUIGreet as display manager, so I only added `services.desktopManager.cosmic.enable = true;` to my config, besides what's mentioned above of course.

**Comment by lilyinstarlight** [comment]
> But is not related to when I try to launch `cosmic-screenshot`.

It's related in that cosmic-screenshot is telling you that it doesn't think `xdg-desktop-portal-cosmic` is running

Can you share the files in `/run/current-system/sw/share/xdg-desktop-portal/*` or share your current configuration so I can poke it myself?

**Comment by Tommimon** [comment]
Well I just updated today and now it works! @freeklucas can you confirm it works on your side?

**Comment by freeklucas** [comment]
> Well I just updated today and now it works! @freeklucas can you confirm it works on your side?
Nope, it still doesn't work for me.

> Can you share the files in `/run/current-system/sw/share/xdg-desktop-portal/*` or share your current configuration so I can poke it myself?
See attachment: [xdg-desktop-portal.tar.gz](https://github.com/user-attachments/files/17192008/xdg-desktop-portal.tar.gz)

**Comment by lilyinstarlight** [comment]
> Edit: Ok, so apparently it's only an issue for me if I start Cosmic using `cosmic-session` from the TTY, it isn't an issue if I use Cosmic-Greeter or TuiGreet. So in my case it was probably user error.

`cosmic-session` is not the command to start COSMIC, that would be `start-cosmic`

Closing since this seems to be resolved. Feel free to reopen if not!
