### ISSUE TITLE
Unable to change power profile in the battery gui

### ISSUE THREAD

**Issue by garare992** [lilyinstarlight/nixos-cosmic#365]
![screenshot-2024-09-26-22-48-45](https://github.com/user-attachments/assets/51babf2f-4c49-4fd0-92b3-43c413c8fea5)

![screenshot-2024-09-26-22-46-24](https://github.com/user-attachments/assets/c6280a17-942d-476b-bf28-51f06cbde6a6)

Nothing happens when i press battery or high performance

**Comment by lilyinstarlight** [comment]
Can you share your NixOS configuration, especially surrounding power settings like power-profiles-daemon or system76-power?

**Comment by garare992** [comment]
> Can you share your NixOS configuration, especially surrounding power settings like power-profiles-daemon or system76-power?

```
{
  config,
  lib,
  pkgs,
  ...
}:
{
  services.desktopManager.cosmic.enable = true;
  services.displayManager.cosmic-greeter.enable = true;
  hardware.system76.enableAll = true;
  services.power-profiles-daemon.enable = false;
}
```
I turned off power-profiles-daemon because I read that it conflicts with system76-power.

**Comment by lilyinstarlight** [comment]
> hardware.system76.enableAll = true;

I don't think you're supposed to do that on non-system76 hardware. I'll try to take a look tomorrow though

**Comment by lilyinstarlight** [comment]
> I turned off power-profiles-daemon because I read that it conflicts with system76-power.

Can you `systemctl status system76-power` to ensure that it is running?

Also can you start `cosmic-settings` from terminal and share terminal output after trying to set a power profile from there?

Thanks!

**Comment by garare992** [comment]
> > I turned off power-profiles-daemon because I read that it conflicts with system76-power.
> 
> Can you `systemctl status system76-power` to ensure that it is running?
> 
> Also can you start `cosmic-settings` from terminal and share terminal output after trying to set a power profile from there?
> 
> Thanks!

![screenshot-2024-10-03-07-15-36](https://github.com/user-attachments/assets/3cf0110a-348e-42ca-a08f-7d8b76cfa71a)

**Comment by lilyinstarlight** [comment]
I can't tell very well because screenshots are hard to read on mobile (well and also in general), but it looks like you don't actually have a working power profiles daemon?

Can you `system76-power profile` from command line and copy/paste output?

**Comment by garare992** [comment]
> I can't tell very well because screenshots are hard to read on mobile (well and also in general), but it looks like you don't actually have a working power profiles daemon?
> 
> Can you `system76-power profile` from command line and copy/paste output?

the System76 power daemon is working in that screenshot. 

```
➜ ~  systemctl status system76-power
● system76-power.service - System76 Power Daemon
     Loaded: loaded (/etc/systemd/system/system76-power.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-10-03 18:23:34 CDT; 1h 16min ago
 Invocation: 42282389c0434f078c3c919289a5ca90
   Main PID: 1082 (system76-power)
         IP: 0B in, 0B out
         IO: 2.6M read, 0B written
      Tasks: 1 (limit: 33227)
     Memory: 3.5M (peak: 4.3M)
        CPU: 2.166s
     CGroup: /system.slice/system76-power.service
             └─1082 /nix/store/c12fgplkqk6xm4z679sn161sdyhmri4i-system76-power-1.1.23/bin/system76-power daemon

Oct 03 18:23:34 nixos system76-power[1082]: [INFO] Disabling NMI Watchdog (for kernel debugging only)
Oct 03 18:23:34 nixos system76-power[1082]: [INFO] Setting automatic graphics power
Oct 03 18:23:34 nixos system76-power[1082]: [WARN] Failed to set automatic graphics power: does not have switchable gr>
Oct 03 18:23:34 nixos system76-power[1082]: [INFO] Initializing with the balanced profile
Oct 03 18:23:34 nixos system76-power[1082]: [INFO] Registering dbus name com.system76.PowerDaemon
Oct 03 18:23:34 nixos system76-power[1082]: [INFO] Adding dbus path /com/system76/PowerDaemon with interface com.syste>
Oct 03 18:23:34 nixos systemd[1]: Started System76 Power Daemon.
Oct 03 18:23:34 nixos system76-power[1082]: [ERROR] fan daemon: platform hwmon not found
Oct 03 18:23:34 nixos system76-power[1082]: [INFO] Handling dbus requests
Oct 03 18:23:34 nixos system76-power[1082]: [ERROR] hid_backlight: no system76_acpi::kbd_backlight led
```

in cosmic-settings, in the power and battery tab, under power mode it says: **Backend not found. Install system76-power  or power profiles daemon.**
```

➜ ~  system76-power profile
Power Profile: ?
Backlight amdgpu_bl1: 255/255 = 100%
Keyboard Backlight tpacpi::kbd_backlight: 2/2 = 100%
```

**Comment by lilyinstarlight** [comment]
Ugh, digging in to this it looks like sys76-power is very out of date and packaged wrong in nixpkgs...

Given you aren't on system76 hardware, I'd probably still recommend going with power-profiles-daemon. But otherwise someone might need to fix this in nixpkgs first (if it wasn't packaged so wrong I could just overlay it here, but it's erroneously in kernelPackages for some awful reason.....)

**Comment by garare992** [comment]
> Ugh, digging in to this it looks like sys76-power is very out of date and packaged wrong in nixpkgs...
> 
> Given you aren't on system76 hardware, I'd probably still recommend going with power-profiles-daemon. But otherwise someone might need to fix this in nixpkgs first (if it wasn't packaged so wrong I could just overlay it here to update, but it's erroneously in kernelPackages for some awful and clearly incorrect reason.....)

Oh, I see. I hope you report it to whoever it concerns so it gets fixed. But yeah, l'll switch to power-profiles-daemon.

Since I'm not using system76 hardware, can I do without `hardware.system76.enableAll = true;`? Or does cosmic depend on it?

**Comment by lilyinstarlight** [comment]
> Since I'm not using system76 hardware, can I do without `hardware.system76.enableAll = true;`? Or does cosmic depend on it?

Yeah that option is intended for system76 hardware is not associated with cosmic at all

**Comment by lilyinstarlight** [comment]
> Oh, I see. I hope you report it to whoever it concerns so it gets fixed.

It looks like there is a PR to fix it upstream that's not been touched (typical nixpkgs experience...): <https://github.com/NixOS/nixpkgs/pull/342921>

**Comment by sjmonson** [comment]
Thanks @lilyinstarlight I'll give that a go! And yeah, as someone who has contributed to other distributions before, I've found the nixpkgs experience quite lacking.

**Comment by RAVENz46** [comment]
For me, issue fixed.
@garare992 how about yours?

**Comment by garare992** [comment]
yes its fixed
