### ISSUE TITLE
Emacs daemon not starting

### ISSUE THREAD

**Issue by garare992** [lilyinstarlight/nixos-cosmic#368]
heres whats in my configuration.nix:
![screenshot-2024-09-27-06-10-37](https://github.com/user-attachments/assets/e381e182-b14e-4e27-a2ac-7950436db0be)

journalctl: 

![screenshot-2024-09-27-06-09-56](https://github.com/user-attachments/assets/01e880d7-ecc0-482d-b385-c67ded8fedec)

**Comment by garare992** [comment]
![screenshot-2024-09-26-22-48-45](https://github.com/user-attachments/assets/1c906ecf-a51d-442e-8880-aa68c6106baa)

**Comment by lilyinstarlight** [comment]
Does this, um, have to do with nixos-cosmic?

**Comment by garare992** [comment]
Probably  not a nixos-cosmic isuse
