### ISSUE TITLE
Getting stuck on these errors when using the 'sudo nixos-rebuild switch --flake' command

### ISSUE THREAD

**Issue by rp1231** [lilyinstarlight/nixos-cosmic#371]
![20240928_185218](https://github.com/user-attachments/assets/d0154695-e3af-4dcc-a80c-067f09dbc736)

How do I solve this?
Thanks

**Comment by lilyinstarlight** [comment]
You're running out of memory trying to build 8 cosmic apps at once presumably at 8 cores each (i.e. 64 threads)

Did you set up the substituter correctly according to readme? If so, you can also try to adjust your flake inputs like the readme specifies to ensure you will always used a cached nixpkgs revision

**Comment by lilyinstarlight** [comment]
> I copied all the code to a flake.nix file according to the readme. I didn't understand what else I'm supposed to do. I've copied the configuration.nix and the hardware-configuration nix to the same folder where I've kept the flake.nix file.

Did you follow this line?

https://github.com/lilyinstarlight/nixos-cosmic/blob/b4f5f62726ada74385f2eec846b47b7fafa876b6/readme.md?plain=1#L43

**Comment by lilyinstarlight** [comment]
Add the nixos module, not the options. Copy-pasting the flake should do that

**Comment by Lemm1** [comment]
> I've created a folder called Flakes located in the home directory and these are the files from that. [Flakes folder.zip](https://github.com/user-attachments/files/17175385/Flakes.folder.zip)

Remove following from configuration.nix:
```
  services.desktopManager.cosmic.enable = true;
  services.displayManager.cosmic-greeter.enable = true;
```
  Perform nixos-rebuild test, add deleted lines back to configuration.nix and do rebuild switch, preferably with -j 1 argument  (or any other sane value for number of jobs that won't overstress your PC)
