### ISSUE TITLE
cosmic-tweaks

### ISSUE THREAD

**Issue by Thatoo** [lilyinstarlight/nixos-cosmic#374]
When https://github.com/NixOS/nixpkgs/issues/345258 will have a Nixos package, I can ping here if you're willing to add it to this flake.

**Comment by lilyinstarlight** [comment]
Nixpkgs COSMIC packages are still generally unhelpful for packaging for use in the desktop environment (even if already packaged in nixpkgs given the problems they have), so I've gone ahead and added cosmic-tweaks in 338c717e405358b46288e666b0baf8403f3f6c52
