### ISSUE TITLE
Cosmic store does not show any apps  

### ISSUE THREAD

**Issue by garare992** [lilyinstarlight/nixos-cosmic#375]
I have flatpak enabled. I have flatpak apps installed. Gnome software center was working for me fine when I was using Gnome. I can now only install flatpak apps via cli. 
![screenshot-2024-09-29-17-53-00](https://github.com/user-attachments/assets/8d4520a7-d0eb-412c-8f14-4ee35fa223ea)

**Comment by lilyinstarlight** [comment]
Do you have user remotes set up?

You can see from output of `flatpak --user remotes`. Readme details how to add a user remote for flatpaks if it's empty (COSMIC Store won't do system remotes): <https://github.com/lilyinstarlight/nixos-cosmic/blob/5b0f33c0fbf07e9d1cec4e15e32bf2e7c1979df1/readme.md?plain=1#L47>

**Comment by garare992** [comment]
> Do you have user remotes set up?
> 
> You can see from output of `flatpak --user remotes`. Readme details how to add a user remote for flatpaks if it's empty (COSMIC Store won't do system remotes):
> 
> https://github.com/lilyinstarlight/nixos-cosmic/blob/5b0f33c0fbf07e9d1cec4e15e32bf2e7c1979df1/radme.md?plain=1#L47

Thanks, I see all the apps now. But I don't see any of my installed flatpak apps in the 'Installed apps' category. How do I fix that?

**Comment by lilyinstarlight** [comment]
What did you change and how did you install flatpak apps if not through COSMIC store?

**Comment by garare992** [comment]
> What did you change and how did you install flatpak apps if not through COSMIC store?

i already had flatpak apps installed from when i was using gnome. i installed them either through cli "flatpak install" or gnome software center.

**Comment by lilyinstarlight** [comment]
> i already had flatpak apps installed from when i was using gnome. i installed them either through cli "flatpak install" or gnome software center.

Can you `flatpak remotes` and remove system remotes if you have them?

As mentioned, COSMIC Store doesn't support them and you probably only have things installed from them (idk if you should just uninstall and reinstall from user remotes or what, but as far as I can tell this no longer has to do with COSMIC)

**Comment by garare992** [comment]
Thank you. I'll close this
