### ISSUE TITLE
Freezing when interacting with applets

### ISSUE THREAD

**Issue by liperium** [lilyinstarlight/nixos-cosmic#382]
I have a weird bug that makes it so in certain use-cases the instant I interact, **my screen freezes for a good ~30s**.

- Clicking on applets to open their context menu
- Right clicking on task bar desktop items ( Run/Pin to app tray )
- Moving windows around (Tiled mode, Super+Drag windows around)

I have a good desktop computer ( 7700x cpu/7800XT, no problem with any other WM/DE ). 
I have the same config on my laptop with no problem. 

Link to video that shows my mouse/screen : [link](https://photos.app.goo.gl/Hp1ZkGwzioFMh854A)

Things tried : 
- Remove other WMs from my config, see if that fixes it.

Maybe this is a bug upstream? ( Will try cosmic desktop popos live image )
e: Added other moments where a similar crash/freeze happens and formatting.

**Comment by liperium** [comment]
Logs (journalctl -b --priority=5) :
Oct 01 22:39:50 battleship dbus-daemon[1036]: [system] Rejected send message, 7 matched rules; type="method_call", sender=":1.53" (uid=1000 pid=2456 comm="cosmic-applet->
Oct 01 22:40:44 battleship dbus-daemon[1036]: [system] Rejected send message, 7 matched rules; type="method_call", sender=":1.53" (uid=1000 pid=2456 comm="cosmic-applet->
lines 362-409/409 (END)

**Comment by lilyinstarlight** [comment]
> Logs (journalctl -b --priority=5) : Oct 01 22:39:50 battleship dbus-daemon[1036]: [system] Rejected send message, 7 matched rules; type="method_call", sender=":1.53" (uid=1000 pid=2456 comm="cosmic-applet-> Oct 01 22:40:44 battleship dbus-daemon[1036]: [system] Rejected send message, 7 matched rules; type="method_call", sender=":1.53" (uid=1000 pid=2456 comm="cosmic-applet-> lines 362-409/409 (END)

Those log lines are cut off. Can you send the whole log lines?

**Comment by liperium** [comment]
I can paste the whole log if you want : [pastebin](https://pastebin.com/UYuyyrjH)
The two last lines happen when I open an applet.

**Comment by lilyinstarlight** [comment]
Ah good, they aren't cut off in the pastebin, thank you!

I don't think there's quite enough logs to determine where it's getting upset. Are you comfy sharing your NixOS config?

I may also give you config options to enable debug logging as well to better pinpoint the error

**Comment by liperium** [comment]
Yes can do, [my nixos configuration](https://github.com/liperium/nix-conf)
It uses flake, and my current machine is "battleship" [folder](https://github.com/liperium/nix-conf/tree/main/hosts/battleship)
Here is the [cosmic-desktop config](https://github.com/liperium/nix-conf/blob/main/modules/desktop/environment/cosmic/default.nix)

is `journalctl -b --priority=5`, appropriate, or should I change the priority? I just went lower in priority, till I saw logs generated by the event. 

Thanks for your work, I really want to respect your time and effort.

**Comment by lilyinstarlight** [comment]
> is `journalctl -b --priority=5`, appropriate, or should I change the priority? I just went lower in priority, till I saw logs generated by the event.

I don't think COSMIC logs any higher than 5 anyway

I'll poke at your config a little and I'll give you options for debug if I still cannot reproduce the issue myself

(also as far as I know, this line should be doing absolutely nothing for you: <https://github.com/liperium/nix-conf/blob/509c45e997caa463a9f31edc4f5ac6f0d7f2e02e/modules/desktop/environment/cosmic/default.nix#L12>)

**Comment by liperium** [comment]
On my laptop I do have system76-power, could that be why it does work? (link to the config file)[https://github.com/liperium/nix-conf/blob/509c45e997caa463a9f31edc4f5ac6f0d7f2e02e/modules/hardware/power-management/system76.nix]

**Comment by lilyinstarlight** [comment]
> On my laptop I do have system76-power, could that be why it does work? [link to the config file](https://github.com/liperium/nix-conf/blob/509c45e997caa463a9f31edc4f5ac6f0d7f2e02e/modules/hardware/power-management/system76.nix)

PPD or sys76-power should both be fine and are tested. I'm figuring it's much more likely due to configuration problems from mixing desktop environments without using specialisations

But I'll find that out when I get a chance to do some testing

**Comment by liperium** [comment]
I have tried removing the other DE's from my modules, but it still would do the same. A really weird bug, but as I can see on the githubs, I am the only one with it aha. If I can help you debug with flags/logs, willing to help!

**Comment by lilyinstarlight** [comment]
Can you `RUST_LOG=debug cosmic-settings` from terminal, make it freeze and then share the output?

**Comment by liperium** [comment]
I do not think I can reproduce the freezes I had in the beginning in cosmic-settings. I do still have the applets freezing the whole system.

**Comment by liperium** [comment]
I just realized that it does even when I **drag windows** around. It may even completely crash my desktop. I will edit first comment.

**Comment by liperium** [comment]
Looks like it is an upstream bug. I just tested cosmic-desktop with the live iso from PopOs! and it seems to be having the same issues/behaviors. Will be making an in depth issue over there. Thank you for your work.
