### ISSUE TITLE
Cosmic closes itself when nixos-rebuild switch

### ISSUE THREAD

**Issue by Thatoo** [lilyinstarlight/nixos-cosmic#383]
When the command
`sudo nixos-rebuild switch --show-trace --flake .#default` is ending, cosmic freeze and closes itself and I'm invited to log into Gnome.
I need to restart to be able to select cosmic again.

**Comment by lilyinstarlight** [comment]
Do you use gdm or cosmic-greeter?

**Comment by Thatoo** [comment]
Both could be an answer?
Here is an extract from my sepcialisation.nix file : 

```
{ config, pkgs, lib, inputs,  ... }:

{
  # Enable the X11 windowing system.
  services.xserver = {
    enable = true;
    displayManager.gdm.enable = lib.mkDefault true;
    desktopManager.gnome.enable = lib.mkDefault true;
  };

  specialisation = {
    gnome.configuration = {
      services.xserver = {
        desktopManager.gnome.enable = true;
        displayManager.gdm.enable = true;
      };
      system.nixos.tags = [ "Gnome" ];
    };
    cosmic.configuration = {
      # Cosmic conflicts with gnome
      services.xserver.desktopManager.gnome.enable = false;
      services.desktopManager.cosmic.enable = true;
        # Cosmic requires cosmic-greeter
      services.xserver.displayManager.gdm.enable = false;
      services.displayManager.cosmic-greeter.enable = true;

      systemd.user.extraConfig = ''DefaultEnvironment="PATH=/run/wrappers/bin:/etc/profiles/per-user/%u/bin:>

      system.nixos.tags = [ "Cosmic" ];
    };
  };
}
```

**Comment by lilyinstarlight** [comment]
`nixos-rebuild switch` kinda sucks in that if you don't specify `--specialisation cosmic`, it will revert to the unspecialised system on switch even if you have a specialisation activated

This isn't a nixos-cosmic thing, see e.g. <https://github.com/NixOS/nixpkgs/pull/207466> which includes some details on that behavior and the `--specialisation` switch

**Comment by Thatoo** [comment]
Thank you so much @lilyinstarlight for teaching me that and sorry for disturbing then.

**Comment by lilyinstarlight** [comment]
No worries! I'm just glad it was a simple problem and not something to debug here :)

**Comment by marionbouder** [comment]
thanks @lilyinstarlight , that helps !
