### ISSUE TITLE
`cosmic-term` starts a nix shell ($SHLVL=2)

### ISSUE THREAD

**Issue by fivegrant** [lilyinstarlight/nixos-cosmic#392]
When I pop open `cosmic-term`, It's shell level is at 2.

```bash
 (nix) me@machine$  pstree $PPID
-+- 03694 five cosmic-term
 \-+= 03726 five /run/current-system/sw/bin/bash
   \--= 03859 five pstree 3694

(nix) me@machine$  echo $SHLVL
2
```

I use [the Starship prompt](https://github.com/starship/starship) and it indicates that it's running in a Nix shell.

Not using home-manager BTW.

**Comment by lilyinstarlight** [comment]
Is this still an issue? I cannot actually replicate this problem

**Comment by addy419** [comment]
@fivegrant I am using starship as well and cannot reproduce this issue.

**Comment by fivegrant** [comment]
This issue seems to have worked itself out now.
