### ISSUE TITLE
error: Undefined variable 'cosmic-wallpapers'

### ISSUE THREAD

**Issue by Pandapip1** [lilyinstarlight/nixos-cosmic#409]
My configuration can be found at https://github.com/Pandapip1/nixos. The only changes from the default branch are that I removed my GNOME configuration from `gavin-laptop-nixos-1.nix` and added

```nix
  services.desktopManager.cosmic.enable = true;
  services.displayManager.cosmic-greeter.enable = true;
```

However, when I try to run it:

```
❯ sudo nixos-rebuild dry-activate --flake .#
building the system configuration...
warning: Git tree '/home/gavin/repos/nixos' is dirty
error:
       … while calling the 'head' builtin
         at /nix/store/y5k9hx0ch578qsizi9p4d310f6b4vhfc-source/lib/attrsets.nix:1575:11:
         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'
         at /nix/store/y5k9hx0ch578qsizi9p4d310f6b4vhfc-source/lib/modules.nix:816:9:
          815|     in warnDeprecation opt //
          816|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          817|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/y5k9hx0ch578qsizi9p4d310f6b4vhfc-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `system.systemBuilderArgs':

       … while evaluating definitions from `/nix/store/y5k9hx0ch578qsizi9p4d310f6b4vhfc-source/nixos/modules/system/activation/activatable-system.nix':

       … while evaluating the option `system.activationScripts.etc.text':

       … while evaluating definitions from `/nix/store/y5k9hx0ch578qsizi9p4d310f6b4vhfc-source/nixos/modules/system/etc/etc-activation.nix':

       … while evaluating definitions from `/nix/store/y5k9hx0ch578qsizi9p4d310f6b4vhfc-source/nixos/modules/system/etc/etc.nix':

       … while evaluating the option `environment.etc.dbus-1.source':

       … while evaluating the option `environment.systemPackages':

       … while evaluating definitions from `/nix/store/63z6hwg3qdmhdaw7ifzjflixp8fm3i16-source/nixos/cosmic/module.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: undefined variable 'cosmic-wallpapers'
       at /nix/store/63z6hwg3qdmhdaw7ifzjflixp8fm3i16-source/nixos/cosmic/module.nix:80:9:
           79|         cosmic-term
           80|         cosmic-wallpapers
             |         ^
           81|         cosmic-workspaces-epoch
```

**Comment by lilyinstarlight** [comment]
Hi there!

Passing `pkgs` in `specialArgs` (here in your code: <https://github.com/Pandapip1/nixos/blob/d2bc49f0c2fd7558d451c8f7f4582d2b71556519/flake.nix#L82>) does problematic things and avoids using the packages in this flake entirely

See https://github.com/lilyinstarlight/nixos-cosmic/issues/315 of which this is a duplicate

**Comment by Pandapip1** [comment]
Oh, that's why none of my nixpkgs options were working, wasn't it. Thanks!

Also, I just opened https://github.com/NixOS/nixpkgs/pull/348146, which should mean that it works even with the `pkgs` in `specialArgs` issue.

**Comment by lilyinstarlight** [comment]
That PR won't actually make anything work with `pkgs` in `specialArgs` either (packages in nixpkgs are still a decent degree of busted). You either need to be adding the overlay from this repository yourself or configure nixpkgs via the `nixpkgs.*` NixOS options as intended

Hopefully that makes sense and sorry for the footgun :)

(I also was considering adding a module assert that checks to make sure a working package set is available and tell people they are silently shadowing some NixOS configuration options via `specialArgs` and need to either fix that or use the escape hatch I posted in the bottom of #315)

**Comment by Pandapip1** [comment]
> Hopefully that makes sense and sorry for the footgun :)

Honestly nixpkgs should add a warning if `pkgs` is in `specialArgs`. I might put together a PR for that.

**Comment by lilyinstarlight** [comment]
Yeah, nixpkgs/`nixosSystem` really should warn on it, but it'll also need an escape hatch to turn off that warning since some people actually intend that behavior (although 99% of the time they can get by with a module that looks like `{ nixpkgs.pkgs = otherpkgs; }`)
