### ISSUE TITLE
Shutdown takes a long time if GeoClue2 service is not enabled

### ISSUE THREAD

**Issue by sezaru** [lilyinstarlight/nixos-cosmic#498]
Not sure if this is a bug or not, but I noticed that shutdown my machine would take a long time (around 1 to 2 minutes) because I didn't have the `GeoClue2` service running and because of that I would get these error messages:

```
cosmic-session[1938]: Failed to watch theme org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.GeoClue2 was not provided by any .service files. Will try again in 25s
```

This would make systemd timeout trying to stop session 3 of my user. Taking around 1m 30s during the shutdown process.

Adding this to my config seems to fix the issue:

```
services.geoclue2.enable = true;
```

Maybe a note about this should be in the troubleshot part of the README?

**Comment by wramalho** [comment]
Thank you for finding out the reason for session 3 interrupting shutdown!

**Comment by lilyinstarlight** [comment]
Should be fixed now on main branch, please update this flake and remove any workarounds you might have had. Feel free to reopen if you're still having issues!
