### ISSUE TITLE
Auto-login option for cosmic-greeter module

### ISSUE THREAD

**Issue by pupbrained** [lilyinstarlight/nixos-cosmic#500]
I use NixOS with LUKS encryption, meaning I have to decrypt my drive on boot. It would be nice to have the option to skip the password prompt before logging into cosmic, if possible, so I don't have to enter two passwords every reboot.

**Comment by lilyinstarlight** [comment]
The normal NixOS autologin options work with greetd, which cosmic-greeter uses. Feel free to re-open if those aren't working for some reason!

**Comment by pupbrained** [comment]
Apologies, but if I may ask, how would I set up the autologin? I know there's a section for it on the [wiki](https://wiki.nixos.org/wiki/Greetd) but that seems to be specifically for setups where the user is using greetd as the sole login system instead of it being the underlying one.

**Comment by drakon64** [comment]
This is a bit of a weird one. On my laptop with auto login set like so:

```nix
services = {
  displayManager = {
    autoLogin = {
      enable = true;
      user = "adamc";
    };
  };
};
```

auto login doesn't work, but with auto login set the same way on the COSMIC Live ISO I build it works. The only difference is that my laptop is pinned to NixOS 24.11 and the ISO's are pinned to NixOS Unstable.

**Comment by lilyinstarlight** [comment]
Oh I think I dreamed yesterday evening that greetd followed those options like every other greeter in NixOS (this is what I get for working while sick). Apologies for that...

@drakon64 The ISO profile probably overrides greeter to use one which does have working autologin

Is there any reason to use cosmic-greeter at all if you're gonna just be doing autologin?

Also,

> where the user is using greetd as the sole login system instead of it being the underlying one.

I'm not sure what this means, but all greetd greeters more or less do logins the same way and instruct which session command to start to the greetd daemon. The autologin config would be on greetd daemon if anywhere (and you'd have to use session command `start-cosmic`)
