### ISSUE TITLE
It seems to build packages even though I am on the unstable branch

### ISSUE THREAD

**Issue by saipavanc** [lilyinstarlight/nixos-cosmic#507]
I am using the following in my flake.nix:
```
{
  description = "Main flake: include configuration.nix and other files";

  inputs = {
    # NixOS official package source, using the nixos-23.11 branch here
    nixos-cosmic.url = "github:lilyinstarlight/nixos-cosmic";
    
    nixos-cosmic = {
      url = "github:lilyinstarlight/nixos-cosmic";
    };
  };

  outputs = { self, nixpkgs, nixos-cosmic, ... }@inputs: {
    # Use hostname
    nixosConfigurations.username = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      specialArgs = { inherit inputs; };
      modules = [
        # for cosmic-de
	{
            nix.settings = {
             substituters = [ "https://cosmic.cachix.org/" ];
              trusted-public-keys = [ "cosmic.cachix.org-1:Dya9IyXD4xdBehWjrkPv6rtxpmMdRel02smYzA85dPE=" ];
            };
        }
	nixos-cosmic.nixosModules.default

        # Import the previous configuration.nix we used,
        # so the old configuration file still takes effect
        ./configuration.nix
      ];
    };
  };
}
```
The readme says that the packages are prebuilt for the unstable branch, but there are many packages which are still being built, and that takes a long time on my machine. Are all the packages not pre-built?

**Comment by saipavanc** [comment]
Okay, I just had to wait for today's update to the cache!

**Comment by lilyinstarlight** [comment]
> Okay, I just had to wait for today's update to the cache!

Yep, sorry about that. CI situation got a little hecked for a few days 😅

It should hopefully be good again within the next day or so!

**Comment by gilest** [comment]
🤔 I think the binary caches might be missing again. Where can we see the status of them? GitHub actions CI result?

Thank you for this package, by the way 🙂

**Comment by lilyinstarlight** [comment]
> Where can we see the status of them? GitHub actions CI result?

Yep! But you'll have to bear with us as we iron out some CI troubles since our old solution wasn't usable anymore

**Comment by drakon64** [comment]
> 🤔 I think the binary caches might be missing again. Where can we see the status of them? GitHub actions CI result?

There's a job running [now](https://github.com/lilyinstarlight/nixos-cosmic/actions/runs/12423067196) and another scheduled for 1AM UTC, I'll check in the morning (around 9AM UTC) to see if anything got stuck and restart anything that did. Either way, caches should be working again once I've completed that.

Hopefully at the weekend I'll be able to implement a more permanent solution so this doesn't keep happening.
