### ISSUE TITLE
Export packages in the flake

### ISSUE THREAD

**Issue by HeitorAugustoLN** [lilyinstarlight/nixos-cosmic#515]
It would be pretty neat if we could acess the packages in an standalone way for those who wanna try the applications without installing the whole desktop. So it can be tested with something like: `nix run github:lilyinstarlight/nixos-cosmic#cosmic-term`

**Comment by lilyinstarlight** [comment]
Does that command not already work for you?

**Comment by HeitorAugustoLN** [comment]
Yeah, it works. I must made some typo when I tried last time.

**Comment by lilyinstarlight** [comment]
No worries! Glad it's working for you :)

**Comment by RAVENz46** [comment]
@lilyinstarlight 
I am very sorry to ask this question here, but why `apps.“<system>”."” <name>”` is not included in flake, why does `nix run` work? I'm stuck on this point in my config, so I'd appreciate it if you could help me out.

**Comment by HeitorAugustoLN** [comment]
> I am very sorry to ask this question here, but why `apps.“<system>”."” <name>”` is not included in flake, why does `nix run` work? I'm stuck on this point in my config, so I'd appreciate it if you could help me out.

`nix run` works with `legacyPackages`, `packages` or `apps`. If no `apps` are defined, `nix run` will look for a package, if no package is defined, it will look for a defined "legacy" package. If none is defined, it will return an error.

**Comment by RAVENz46** [comment]
> `nix run` works with `legacyPackages`, `packages` or `apps`. If no `apps` are defined, `nix run` will look for a package, if no package is defined, it will look for a defined "legacy" package. If none of these is defined, it will return an error.

Oh, I didn't know that.
I confirm that `nix run` works on my config.
Thank you!
