### ISSUE TITLE
apps that use dconf cannot read profile after update

### ISSUE THREAD

**Issue by michaelBelsanti** [lilyinstarlight/nixos-cosmic#517]
After #510 easyeffects has started launching with the error `unable to open named profile (/usr/share/dconf/profile/cosmic): using the null configuration.` After launching with the error, the GUI mostly works as expected, but there is no audio output and most of the settings cannot be edited. 

This issue starts occurring after updating just the cosmic input. I'm not sure if this error is specific to NixOS, but the fact that it's referencing a path that wouldn't exist on this distro makes me think it might be.

Edit: This seems to affects all apps that use dconf

**Comment by michaelBelsanti** [comment]
I assume its related to [this commit](https://github.com/pop-os/cosmic-session/commit/87a0644435145b009ea4c159d3992ff279292424#diff-9f2b95c89da3f2df9b3db90dfa3b7ea041a7251eabce8e202db049b92a02a7f7).

**Comment by lilyinstarlight** [comment]
> I assume its related to [this commit](https://github.com/pop-os/cosmic-session/commit/87a0644435145b009ea4c159d3992ff279292424#diff-9f2b95c89da3f2df9b3db90dfa3b7ea041a7251eabce8e202db049b92a02a7f7).

Close, but it appears to be this one: https://github.com/pop-os/cosmic-session/commit/78316ba39c53fccad448c7a2a48fd898b3ab9d86

**Comment by michaelBelsanti** [comment]
yep, stumbled on that one just a few minutes after the other

**Comment by michaelBelsanti** [comment]
in case anyone else runs into it, some apps still have this problem after the fix, but I assume that either an issue with the apps or upstream.
