### ISSUE TITLE
Custom keyboard layouts (XKB)

### ISSUE THREAD

**Issue by pwall2222** [lilyinstarlight/nixos-cosmic#528]
## Prior explanation
pop-os/xkb-data uses `X11_BASE_RULES_XML` and `X11_EXTRA_RULES_XML` insead of the more usual `XKB_CONFIG_ROOT` that nixpkgs itself uses for [custom layouts](https://github.com/NixOS/nixpkgs/blob/314e12ba369ccdb9b352a4db26ff419f7c49fa84/nixos/modules/services/x11/extra-layouts.nix#L144C7-L144C22), which depends on creating a [custom xkeyboard_config package](https://github.com/NixOS/nixpkgs/blob/314e12ba369ccdb9b352a4db26ff419f7c49fa84/pkgs/servers/x11/xorg/overrides.nix#L679).

## Issue

Inside the 3 wrappers that set `X11_BASE_RULES_XML` and `X11_EXTRA_RULES_XML`:

https://github.com/lilyinstarlight/nixos-cosmic/blob/23f90212a1328af7438b99199e68f85fe6ccab19/pkgs/cosmic-applets/package.nix#L82-L83
https://github.com/lilyinstarlight/nixos-cosmic/blob/23f90212a1328af7438b99199e68f85fe6ccab19/pkgs/cosmic-greeter/package.nix#L82-L83
https://github.com/lilyinstarlight/nixos-cosmic/blob/23f90212a1328af7438b99199e68f85fe6ccab19/pkgs/cosmic-settings/package.nix#L102-L103

The environment variables are all set with `--set`, which makes them unmodifiable at run time.

## Resolve

The simplest way to resolve this is just to use `--set-default` instead, so the user is at least able to set it on it's own. But it would be great if it could be adapted to use `XKB_CONFIG_ROOT`.
(although that I don't quite know if this is enough to make custom layouts work overall, I haven't looked where they actually get used for translating input).

## Workarounds

An easy work around for the time being is using this replacement:

```
system.replaceDependencies.replacements = [
  {
    oldDependency = pkgs.xkeyboard_config;
    newDependency = pkgs.xorg.xkeyboardconfig_custom {
      layouts = config.services.xserver.xkb.extraLayouts;
    };
  }
];
```

**Comment by lilyinstarlight** [comment]
I've changed the packages to use `--set-default` in #524 

I'll also later add to the module to set the relevant env vars based on `config.services.xserver.xkb.dir` though, which would effectively be equivalent to using `XKB_CONFIG_ROOT` (which otherwise upstream xkb-data <https://github.com/pop-os/xkb-data/blob/c9f94ec778895c9dfbad37bf282659cfb39c3dea/src/lib.rs#L91-L109> would have to be patched for support for `XKB_CONFIG_ROOT`)

**Comment by pwall2222** [comment]
>which would otherwise require upstream xkb-data to be patched for support

I already opened a issue upstream [xkb-data/5](https://www.github.com/pop-os/xkb-data/issues/5)

> I've changed the packages to use --set-default
> I'll also add to the module to set the relevant env vars

Thank you very much!!
