### ISSUE TITLE
cachix miss on stable

### ISSUE THREAD

**Issue by ccalhoun1999** [lilyinstarlight/nixos-cosmic#535]
I'm trying to upgrade my system today (on stable), but it's trying to rebuild cosmic from source (which I've never been able to do even with reduced core count and it takes a long time). Is the cache not updated yet? Or is there something wrong with my flake? I've had the cache hit before so it's a bit confusing. I also tried disabling cosmic, doing nixos-rebuild test, and then re-enabling cosmic but it still tries to compile.

**Comment by lilyinstarlight** [comment]
See <https://github.com/lilyinstarlight/nixos-cosmic/issues/507#issuecomment-2556010230>, we've been having some CI troubles that have exacerbated the cache situation

We should have cache populated again once #524 finishes building

**Comment by ccalhoun1999** [comment]
Didn't realize you could see the status of the cache build in GitHub actions. It's rebuilding now so my timing must have been a bit unlucky!

**Comment by lilyinstarlight** [comment]
I do plan on setting up storepath pinning for cachix at some point to help the problem of repeatedly failing intermediate builds filling up the cache and evicting old storepaths when updates get stalled for a few days :)

**Comment by lilyinstarlight** [comment]
Pinning was easier than I anticipated, so I've actually gone ahead and implemented that locally and will push once #524 merges (so that it doesn't start parallel CI runs, which we still aren't able to do yet for a few more days until CI is finished being reworked and cloud quotas get upped)
