### ISSUE TITLE
Is this repo only updated with the major releases

### ISSUE THREAD

**Issue by authenticastrology** [lilyinstarlight/nixos-cosmic#536]
Thanks for all the time and energy you are putting into this. Just out of curiosity, I was wondering if this repo is regularly updated in alignment with the smaller updates by Pop or is it a tagged release. Asking because I like using Nix, but wondering if this is only updated with the major releases from Pop. Though it appears there is regular updating, I just wanted to confirm. Thanks in advance for letting me waffle...lol.

**Comment by lilyinstarlight** [comment]
It is updated daily automatically from upstream repositories (sorta like Pop is now with cosmic packages last I checked but I think those git revs are bumped by hand every few days)

There will be a branch on this repository that uses releases once they get closer to actual releases and we don't constantly need COSMIC updates and fixes for a working desktop environment
