### ISSUE TITLE
Build fails on stable/nixos-23.11: Error building iced_core

### ISSUE THREAD

**Issue by Tyler-Hardin** [lilyinstarlight/nixos-cosmic#55]
I'm not sure what's wrong with my system, but I can't get any commits from `47fafe15a2705bf48af43b7fae58159fee657419` (from March 1st) until now to build.

```
error: builder for '/nix/store/8ab28kwzpar1l62ydh85a33yfv4rizas-iced_core-0.12.0.drv' failed with exit code 1;
       last 10 log lines:
       > Traceback (most recent call last):
       >   File "/nix/store/r4rksmam6h4bc72nf3dpwgq79yixcykc-replace-workspace-values", line 108, in <module>
       >     main()
       >   File "/nix/store/r4rksmam6h4bc72nf3dpwgq79yixcykc-replace-workspace-values", line 88, in main
       >     changed |= replace_key(
       >                ^^^^^^^^^^^^
       >   File "/nix/store/r4rksmam6h4bc72nf3dpwgq79yixcykc-replace-workspace-values", line 32, in replace_key
       >     workspace_copy = workspace_manifest[section][key]
       >                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^
       > KeyError: 'package'
       For full logs, run 'nix log /nix/store/8ab28kwzpar1l62ydh85a33yfv4rizas-iced_core-0.12.0.drv'.
error: 1 dependencies of derivation '/nix/store/61rxch9q8j6c43s8r3dd2gvlz9f22brz-cargo-vendor-dir.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qq8c4l6b03bnl2wfibs8c6zrmgp21c34-cargo-vendor-dir.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7py1cp7x1c2cm78wpzh6dxj8w31hjcbz-cosmic-edit-0-unstable-2024-02-28.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8pfjy46sfvms6gflr4m767lnnxw3zma3-system-path.drv' failed to build
```

**Comment by Tyler-Hardin** [comment]
Ah, that was the issue. Thank you! And thanks for your work putting this together. I've been itching to try Cosmic for a long time.

**Comment by Thatoo** [comment]
Could it be possible to re-open this issue (maybe change the title) to track till unstable won't be necessary anymore?
People could subscribe to it and when unstable won't be necessary, a post would be added and the issue closed?

**Comment by Tyler-Hardin** [comment]
I'll reopen for now and leave it up to Lily when to close it.

**Comment by lilyinstarlight** [comment]
Unstable will be necessary until 24.05 release next month. It will not work with 23.11 and this is not intended to be worked on

I'm open to leaving this issue open until the 24.05 release for discoverability reasons, though!

Or we could leave it closed as "not planned" and just pin it so it still shows up on the issue page
