### ISSUE TITLE
Perhaps I am doing this wrong? Nix Flake Update

### ISSUE THREAD

**Issue by authenticastrology** [lilyinstarlight/nixos-cosmic#561]
Hello, 
I might be doing this wrong, but I have been trying to update my flake which is in my /etc/nixos folder. My host name is nixos and I will share the flake below. But here is what is happening. When I try to update using sudo nix flake update --flake ./#nixos from inside of my /etc/nixos folder, it is returning the following error.

error: unexpected fragment 'nixos' in flake reference './#nixos'

Here is my flake file:

{
  inputs = {
    nixpkgs.follows = "nixos-cosmic/nixpkgs"; # NOTE: change "nixpkgs" to "nixpkgs-stable" to use stable NixOS release

    nixos-cosmic.url = "github:lilyinstarlight/nixos-cosmic";
  };

  outputs = { self, nixpkgs, nixos-cosmic }: {
    nixosConfigurations = {
      # NOTE: change "host" to your system's hostname
      nixos = nixpkgs.lib.nixosSystem {
        modules = [
          {
            nix.settings = {
              substituters = [ "https://cosmic.cachix.org/" ];
              trusted-public-keys = [ "cosmic.cachix.org-1:Dya9IyXD4xdBehWjrkPv6rtxpmMdRel02smYzA85dPE=" ];
            };
          }
          nixos-cosmic.nixosModules.default
          ./configuration.nix
        ];
      };
    };
  };
}

Am I doing this right? I just recently reinstalled and I could have sworn with my last install that the same command was working correctly.

**Comment by lilyinstarlight** [comment]
You should be able to just do `sudo nix flake update` or `sudo nix flake update --flake /etc/nixos` (i.e. remove the reference) if that's where your flake is to update inputs. You'll still need to also build a new system generation (e.g. `sudo nixos-rebuild switch`) with the updated inputs

Feel free to ask in Nix/NixOS support channels if you're having further issues using the Nix CLI!
