### ISSUE TITLE
readme.md code

### ISSUE THREAD

**Issue by crftbt** [lilyinstarlight/nixos-cosmic#78]
Was curious where the code listed in readme.md goes. I tried pasting it into /etc/nixos/configuration.nix but that just seems to cause nixos-rebuild switch to throw errors. :(

**Comment by RAVENz46** [comment]
You should enable flake and add readme code to flake.nix.
[This one](https://github.com/Misterio77/nix-starter-configs) is one of the good start point to try flake.

**Comment by dmyTRUEk** [comment]
You can see how i made it in my nixos config [here](https://github.com/dmyTRUEk/nixos-config/commit/139bdee99d330f43f52e17eb798d1a5623dc751d).

**Comment by lilyinstarlight** [comment]
I'll go ahead and close this, but do please re-open if you found anything else unclear!
