### ISSUE TITLE
Cannot Enable

### ISSUE THREAD

**Issue by milesje** [lilyinstarlight/nixos-cosmic#88]
When adding the flake setup I'm getting the following error.

```
error: The option `services.displayManager.enable' does not exist. Definition values:
       - In `/nix/store/g99nl5kn6s7vhgiadklmli9qnxqhwpf0-source/nixos/cosmic-greeter/module.nix':
           {
             _type = "if";
             condition = false;
             content = true;
           }
```
I have NOT made any changes to my configuration.nix to actually enable cosmic yet.
I do have both Hyprland and Gnome enabled.

I've attached my flake.nix file
[flake.nix.txt](https://github.com/lilyinstarlight/nixos-cosmic/files/15178772/flake.nix.txt)

**Comment by lilyinstarlight** [comment]
Make sure you have nixos-unstable up-to-date. Also note that you may want to enable it in a specialisation that does not enable GNOME, because of #17

**Comment by milesje** [comment]
AFAIK I have nixos-unstable up-to-date.... I'm not sure I know how to "enable it in a specialisation".

**Comment by lilyinstarlight** [comment]
Can you share nixpkgs rev from flake.lock file?

(we'll worry about specialisation later, if/when it becomes a problem)

**Comment by milesje** [comment]
Not 100% sure this is what you are after...
```
"nixpkgs": {
      "locked": {
        "lastModified": 1708807242,
        "narHash": "sha256-sRTRkhMD4delO/hPxxi+XwLqPn8BuUq6nnj4JqLwOu0=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "73de017ef2d18a04ac4bfd0c02650007ccb31c2a",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
```

I'm also attaching the flake.lock file in case it isn't...
[flake.lock.txt](https://github.com/lilyinstarlight/nixos-cosmic/files/15178962/flake.lock.txt)

**Comment by lilyinstarlight** [comment]
Yeah, could you run `nix flake update`? https://github.com/NixOS/nixpkgs/commit/73de017ef2d18a04ac4bfd0c02650007ccb31c2a is from months ago

**Comment by milesje** [comment]
That appears to have fixed it!

**Comment by lilyinstarlight** [comment]
Awesome, glad it was that easy :)
