### ISSUE TITLE
Display Manager and Window Manager

### ISSUE THREAD

**Issue by crftbt** [lilyinstarlight/nixos-cosmic#99]
Is greetd the display manager and cosmic-session the window manager in this flake? 
Is this temporary to get the pre alpha working, or is this what will be used once cosmic is part of nix packages?

**Comment by lilyinstarlight** [comment]
> Is greetd the display manager and cosmic-session the window manager in this flake?

cosmic-greeter (under greetd) is display manager and "window manager" isn't exactly a concept that applies here, but COSMIC is the desktop environment and cosmic-comp specifically is the wayland compositor

> Is this temporary to get the pre alpha working, or is this what will be used once cosmic is part of nix packages?

Yes this repo is temporary for ensuring COSMIC is working for when there are tagged releases that can added to nixpkgs
